michalsoida/__init__.py
from .webapp import app

michalsoida/database/__init__.py
from peewee import DoesNotExist, JOIN

from .peewee import db
from .auth import User
from .project import Project
from .tracking import PrintStorage, PostgresStorage, Tracking

michalsoida/database/auth.py
from flask_login import UserMixin
from passlib.context import CryptContext
from passlib.pwd import genword
from peewee import CharField, TextField, DoesNotExist

from .peewee import BaseModel

pwd_context = CryptContext(schemes=['sha512_crypt'])


class User(BaseModel, UserMixin):

    username = CharField(unique=True)
    _password = TextField()
    session_token = CharField(unique=True)
    apikey = CharField(unique=True)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, password):
        self._password = pwd_context.encrypt(password)
        self.session_token = genword(length=50)

    @password.deleter
    def password(self):
        del self._password
        del self.session_token

    def verify_password(self, password):
        if self.password is None:
            return False
        valid, new_hash = pwd_context.verify_and_update(password,
                                                        self.password)
        if valid:
            if new_hash:
                self._password = new_hash
                self.session_token = genword(length=50)
                self.save()
            return True
        return False

    def get_id(self):
        return self.session_token


tables_to_create = [
    User,
]

michalsoida/frontend/__init__.py
from .blueprint import frontend

michalsoida/frontend/blueprint.py
from flask import (Blueprint, render_template, make_response,
                   url_for, request, abort, flash, redirect)
from flask_login import (current_user, login_required, login_url)
from webargs import fields, validate
from webargs.flaskparser import use_kwargs

from ..database import Project
from ..functions import get_mimetype


frontend = Blueprint('frontend', __name__, template_folder='templates')


@frontend.route('/favicon.ico')
def favicon_ico():
    return redirect(url_for('static', filename='favicon.ico'))


@frontend.route('/robots.txt')
def robots_txt():
    return 'User-agent: *\nDisallow: \n'


@frontend.route('/')
def index():
    return render_template('frontend/o-mnie.html')


@frontend.route('/cv/')
def cv():
    project = Project.get(Project.title_pl == 'CV')
    return render_template('frontend/cv.html', project=project,
                           user=current_user)


@frontend.route('/kontakt/')
def kontakt():
    return render_template('frontend/kontakt.html')


@frontend.route('/projekty/')
def projekty():
    projects = Project.select().order_by(Project.title_pl)
    return render_template('frontend/projekty.html', projects=projects,
                           user=current_user)


@frontend.route('/o-stronie/')
def o_stronie():
    return render_template('frontend/o-stronie.html')


@frontend.route('/en/')
def en_index():
    return render_template('frontend/about-me.html', english=True)


@frontend.route('/en/cv/')
def en_cv():
    project = Project.get(Project.title_pl == 'CV')
    return render_template('frontend/cv.html', project=project,
                           user=current_user, english=True)


@frontend.route('/en/contact/')
def en_contact():
    return render_template('frontend/kontakt.html', english=True)


@frontend.route('/en/projects/')
def en_projects():
    projects = Project.select().order_by(Project.title_en)
    return render_template('frontend/projekty.html', english=True,
                           projects=projects, user=current_user)


@frontend.route('/en/about-page/')
def en_about_page():
    return render_template('frontend/about-page.html', english=True)


@frontend.route('/apple-touch-icon-precomposed.png')
@frontend.route('/apple-touch-icon-144x144-precomposed.png')
def apple_touch_icon():
    return redirect(url_for('static',
                            filename='apple-touch-icon-precomposed.png'))


@frontend.route('/keybase.txt')
@frontend.route('/.well-known/keybase.txt')
def keybase_txt():
    return redirect(url_for('static', filename='keybase.txt'))


@frontend.route('/o-mnie/')
@frontend.route('/index.html')
@frontend.route('/index.php')
def red_index():
    return redirect(url_for('index'))


projekty_edit_args = {
    'project_id': fields.Int(required=True),
}


@frontend.route('/projekty/edit/')
@login_required
@use_kwargs(projekty_edit_args)
def projekty_edit(project_id):
    project = Project.get_by_id(project_id)
    return render_template('frontend/projekty-edit.html', project=project)


save_project_args = {
    'project_id': fields.Int(required=True),
    'title_pl': fields.Str(required=True),
    'title_en': fields.Str(required=True),
    'description_pl': fields.Str(required=True),
    'description_en': fields.Str(required=True),
    'content_pl': fields.Str(required=True),
    'content_en': fields.Str(required=True),
    'data': fields.Raw(location='files', missing=None),
}


@frontend.route('/edit/submit', methods=['POST'])
@login_required
@use_kwargs(save_project_args)
def save_project(project_id, title_pl, title_en, description_pl,
                 description_en, content_pl, content_en, data):
    project = Project.get_by_id(project_id)
    project.title_pl = title_pl
    project.title_en = title_en
    project.description_pl = description_pl
    project.description_en = description_en
    project.content_pl = content_pl
    project.content_en = content_en

    if data is not None:
        data = data.read()
        project.thumbnail = data
        project.thumbnail_mimetype = get_mimetype(data)

    project.save()
    return redirect(url_for('.projekty'))

michalsoida/functions/__init__.py
from .functions import (make_jpg_response, make_pdf_response,
                        make_png_response, make_svg_response,
                        get_mimetype)

michalsoida/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Michał Soida">
	<meta name="description" content="Prywatna strona Michała Soidy">
	<link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.png') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
	{%- block head %}{% endblock %}
	<title>{% block title %}{% endblock %}</title>
</head>
<body class="{% block body_class %}default{% endblock %}"><div id="outerWrapper">
	<header>
	<h1>
		<img width="18" height="18" src="{{ url_for('static', filename='s_logo.svg') }}" alt="logo"> {% if english -%}
		My corner on the internet
		{%- else -%}
		Mój kąt w internecie
		{%- endif %}
	</h1>
	<nav><hr>
{%- if english %}
{%- set navigation = [dict(title="About me", url=url_for('frontend.en_index')), dict(title="CV", url=url_for('frontend.en_cv')), dict(title="Contact", url=url_for('frontend.en_contact')), dict(title="My projects", url=url_for('frontend.en_projects')), dict(title="About this page", url=url_for('frontend.en_about_page')), dict(title="Wersja polska", url=url_for('frontend.index'))] -%}
{%- else %}
{%- set navigation = [dict(title="O mnie", url=url_for('frontend.index')), dict(title="CV", url=url_for('frontend.cv')), dict(title="Kontakt", url=url_for('frontend.kontakt')), dict(title="Moje projekty", url=url_for('frontend.projekty')), dict(title="O stronie", url=url_for('frontend.o_stronie')), dict(title="English version", url=url_for('frontend.en_index'))] -%}
{%- endif %}
{%- for link in navigation -%}
{%- if not loop.first %}
	<span class="hidden"> - </span>
{%- endif -%}
{%- if self.title() ==  link.title %}
	<span>{{ link.title }}</span>
{%- else -%}
	<a href="{{ link.url }}">{{ link.title }}</a>
{%- endif -%}
{%- endfor %}
	<hr></nav>
	</header>
{%- with messages = get_flashed_messages() -%}
{%- if messages %}
	<section id="message">
		{%- for message in messages %}
		{{ message }}<br>
		{%- endfor %}
	</section><br>
{%- endif -%}
{%- endwith %}
	<div id="contentWrapper">
	<section id="content">
{%- block content %}{% endblock %}
	</section>
	</div>
	<footer><hr>&copy; Copyright by <a href="http://michal.soida.pl/">Michał Soida</a>.<span> {% if english -%}
		(Your browser does not support CSS. This is text-only version.)
		{%- else -%}
		(Twoja przeglądarka nie obsługuje CSS. Przeglądasz wersję tekstową.)
		{%- endif -%}
	</span><img width="50" height="24" src="{{ url_for('static', filename='soida_logo.svg') }}" alt="logo"></footer>
</div></body>
</html>

michalsoida/templates/error-404.html
{% extends "error.html" %}
{% block title %}Błąd 404{% endblock %}
{% block name %}Błąd 404: Strona nie została odnaleziona{% endblock %}
{% block desc -%}
<p>Jeżeli strona o takim adresie powinna istnieć, <a href="{{ url_for('frontend.kontakt') }}">poinformuj mnie</a> o błędzie.</p>
{%- endblock %}

michalsoida/templates/error.html
{% extends "base.html" %}
{% block body_class %}red{% endblock %}
{% block title %}{{ error_code|safe }} {{ error_name|safe }}{% endblock %}
{% block content %}
	<h1>{% block name %}{{ error_name|safe }}{% endblock %}</h1>
	{% block desc %}{{ error_description|safe }}{% endblock %}
	<a href="{{ url_for('frontend.index') }}">Wróć na stronę główną</a>
{%- if messages is defined %}
	<br>
	<ul>
{%- for message in messages %}
		<li>{{ message }}</li>
{%- endfor %}
	</ul>
{%- endif %}
{%- endblock %}